name: Checkov IaC Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Checkov Action
        uses: bridgecrewio/checkov-action@master
        with:
          # Target the AWS folder directly to ignore Azure and GCP
          directory: aws/
          framework: terraform
          # Export results to JSON format for DefectDojo integration
          output_format: json
          output_file_path: checkov_report.json
          # Prevent pipeline failure so the report can be generated and uploaded
          soft_fail: true

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-json-report
          path: checkov_report.json
